from app.models import db, Lesson, Word, Phrase, environment, SCHEMA
from sqlalchemy.sql import text


def seed_lessons():

    words = [
    Word(word="I", translation="", part_of_speech="Pronoun"),
    Word(word="me", translation="", part_of_speech="Pronoun"),
    Word(word="you", translation="", part_of_speech="Pronoun"),
    Word(word="he", translation="", part_of_speech="Pronoun"),
    Word(word="she", translation="", part_of_speech="Pronoun"),
    Word(word="it", translation="", part_of_speech="Pronoun"),
    Word(word="we", translation="", part_of_speech="Pronoun"),
    Word(word="they", translation="", part_of_speech="Pronoun"),
    Word(word="my", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="your", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="his", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="her", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="its", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="our", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="their", translation="", part_of_speech="Possessive Pronoun"),
    Word(word="big", translation="", part_of_speech="Adjective"),
    Word(word="small", translation="", part_of_speech="Adjective"),
    Word(word="happy", translation="", part_of_speech="Adjective"),
    Word(word="sad", translation="", part_of_speech="Adjective"),
    Word(word="good", translation="", part_of_speech="Adjective"),
    Word(word="bad", translation="", part_of_speech="Adjective"),
    Word(word="hot", translation="", part_of_speech="Adjective"),
    Word(word="cold", translation="", part_of_speech="Adjective"),
    Word(word="new", translation="", part_of_speech="Adjective"),
    Word(word="old", translation="", part_of_speech="Adjective"),
    Word(word="go", translation="", part_of_speech="Verb"),
    Word(word="come", translation="", part_of_speech="Verb"),
    Word(word="eat", translation="", part_of_speech="Verb"),
    Word(word="drink", translation="", part_of_speech="Verb"),
    Word(word="sleep", translation="", part_of_speech="Verb"),
    Word(word="walk", translation="", part_of_speech="Verb"),
    Word(word="run", translation="", part_of_speech="Verb"),
    Word(word="play", translation="", part_of_speech="Verb"),
    Word(word="work", translation="", part_of_speech="Verb"),
    Word(word="study", translation="", part_of_speech="Verb"),
    Word(word="the", translation="", part_of_speech=""),
    Word(word="be", translation="", part_of_speech=""),
    Word(word="and", translation="", part_of_speech=""),
    Word(word="of", translation="", part_of_speech=""),
    Word(word="a", translation="", part_of_speech=""),
    Word(word="in", translation="", part_of_speech=""),
    Word(word="to", translation="", part_of_speech=""),
    Word(word="have", translation="", part_of_speech=""),
    Word(word="create", translation="", part_of_speech=""),
    Word(word="that", translation="", part_of_speech=""),
    Word(word="for", translation="", part_of_speech=""),
    Word(word="with", translation="", part_of_speech=""),
    Word(word="on", translation="", part_of_speech=""),
    Word(word="repeat", translation="", part_of_speech=""),
    Word(word="say", translation="", part_of_speech=""),
    Word(word="this", translation="", part_of_speech=""),
    Word(word="us", translation="", part_of_speech=""),
    Word(word="at", translation="", part_of_speech=""),
    Word(word="but", translation="", part_of_speech=""),
    Word(word="nice", translation="", part_of_speech=""),
    Word(word="add", translation="", part_of_speech=""),
    Word(word="from", translation="", part_of_speech=""),
    Word(word="favorite", translation="", part_of_speech=""),
    Word(word="not", translation="", part_of_speech=""),
    Word(word="by", translation="", part_of_speech=""),
    Word(word="mom", translation="", part_of_speech=""),
    Word(word="or", translation="", part_of_speech=""),
    Word(word="grandpa", translation="", part_of_speech=""),
    Word(word="brother", translation="", part_of_speech=""),
    Word(word="dad", translation="", part_of_speech=""),
    Word(word="can", translation="", part_of_speech=""),
    Word(word="who", translation="", part_of_speech=""),
    Word(word="get", translation="", part_of_speech=""),
    Word(word="if", translation="", part_of_speech=""),
    Word(word="would", translation="", part_of_speech=""),
    Word(word="sister", translation="", part_of_speech=""),
    Word(word="pretty", translation="", part_of_speech=""),
    Word(word="make", translation="", part_of_speech=""),
    Word(word="about", translation="", part_of_speech=""),
    Word(word="know", translation="", part_of_speech=""),
    Word(word="will", translation="", part_of_speech=""),
    Word(word="up", translation="", part_of_speech=""),
    Word(word="one", translation="", part_of_speech=""),
    Word(word="time", translation="", part_of_speech=""),
    Word(word="there", translation="", part_of_speech=""),
    Word(word="year", translation="", part_of_speech=""),
    Word(word="so", translation="", part_of_speech=""),
    Word(word="think", translation="", part_of_speech=""),
    Word(word="dog", translation="", part_of_speech=""),
    Word(word="which", translation="", part_of_speech=""),
    Word(word="them", translation="", part_of_speech=""),
    Word(word="some", translation="", part_of_speech=""),
    Word(word="people", translation="", part_of_speech=""),
    Word(word="take", translation="", part_of_speech=""),
    Word(word="out", translation="", part_of_speech=""),
    Word(word="into", translation="", part_of_speech=""),
    Word(word="just", translation="", part_of_speech=""),
    Word(word="see", translation="", part_of_speech=""),
    Word(word="him", translation="", part_of_speech=""),
    Word(word="now", translation="", part_of_speech=""),
    Word(word="could", translation="", part_of_speech=""),
    Word(word="than", translation="", part_of_speech=""),
    Word(word="what", translation="", part_of_speech=""),
    Word(word="like", translation="", part_of_speech=""),
    Word(word="other", translation="", part_of_speech=""),
    Word(word="how", translation="", part_of_speech=""),
    Word(word="then", translation="", part_of_speech=""),
    Word(word="two", translation="", part_of_speech=""),
    Word(word="more", translation="", part_of_speech=""),
    Word(word="these", translation="", part_of_speech=""),
    Word(word="want", translation="", part_of_speech=""),
    Word(word="way", translation="", part_of_speech=""),
    Word(word="look", translation="", part_of_speech=""),
    Word(word="first", translation="", part_of_speech=""),
    Word(word="also", translation="", part_of_speech=""),
    Word(word="son", translation="", part_of_speech=""),
    Word(word="because", translation="", part_of_speech=""),
    Word(word="day", translation="", part_of_speech=""),
    Word(word="use", translation="", part_of_speech=""),
    Word(word="no", translation="", part_of_speech=""),
    Word(word="man", translation="", part_of_speech=""),
    Word(word="girl", translation="", part_of_speech=""),
    Word(word="find", translation="", part_of_speech=""),
    Word(word="here", translation="", part_of_speech=""),
    Word(word="thing", translation="", part_of_speech=""),
    Word(word="give", translation="", part_of_speech=""),
    Word(word="many", translation="", part_of_speech=""),
    Word(word="well", translation="", part_of_speech=""),
    Word(word="only", translation="", part_of_speech=""),
    Word(word="those", translation="", part_of_speech=""),
    Word(word="tell", translation="", part_of_speech=""),
    Word(word="boy", translation="", part_of_speech=""),
    Word(word="woman", translation="", part_of_speech=""),
    Word(word="even", translation="", part_of_speech=""),
    Word(word="back", translation="", part_of_speech=""),
    Word(word="any", translation="", part_of_speech=""),
    Word(word="daughter", translation="", part_of_speech=""),
    Word(word="grandma", translation="", part_of_speech=""),
    Word(word="life", translation="", part_of_speech=""),
    Word(word="child", translation="", part_of_speech=""),
    Word(word="they're", translation="", part_of_speech=""),
    Word(word="interview", translation="", part_of_speech=""),
    Word(word="down", translation="", part_of_speech=""),
    Word(word="may", translation="", part_of_speech=""),
    Word(word="after", translation="", part_of_speech=""),
    Word(word="before", translation="", part_of_speech=""),
    Word(word="should", translation="", part_of_speech=""),
    Word(word="wood", translation="", part_of_speech=""),
    Word(word="morning", translation="", part_of_speech=""),
    Word(word="afternoon", translation="", part_of_speech=""),
    Word(word="food", translation="", part_of_speech=""),
    Word(word="school", translation="", part_of_speech=""),
    Word(word="call", translation="", part_of_speech=""),
    Word(word="world", translation="", part_of_speech=""),
    Word(word="hello", translation="", part_of_speech=""),
    Word(word="hi", translation="", part_of_speech=""),
    Word(word="later", translation="", part_of_speech=""),
    Word(word="meet", translation="", part_of_speech=""),
    Word(word="still", translation="", part_of_speech=""),
    Word(word="try", translation="", part_of_speech=""),
    Word(word="as", translation="", part_of_speech=""),
    Word(word="last", translation="", part_of_speech=""),
    Word(word="ask", translation="", part_of_speech=""),
    Word(word="need", translation="", part_of_speech=""),
    Word(word="too", translation="", part_of_speech=""),
    Word(word="feel", translation="", part_of_speech=""),
    Word(word="three", translation="", part_of_speech=""),
    Word(word="second", translation="", part_of_speech=""),
    Word(word="when", translation="", part_of_speech=""),
    Word(word="state", translation="", part_of_speech=""),
    Word(word="never", translation="", part_of_speech=""),
    Word(word="become", translation="", part_of_speech=""),
    Word(word="between", translation="", part_of_speech=""),
    Word(word="high", translation="", part_of_speech=""),
    Word(word="really", translation="", part_of_speech=""),
    Word(word="something", translation="", part_of_speech=""),
    Word(word="most", translation="", part_of_speech=""),
    Word(word="another", translation="", part_of_speech=""),
    Word(word="much", translation="", part_of_speech=""),
    Word(word="family", translation="", part_of_speech=""),
    Word(word="own", translation="", part_of_speech=""),
    Word(word="pet", translation="", part_of_speech=""),
    Word(word="leave", translation="", part_of_speech=""),
    Word(word="put", translation="", part_of_speech=""),
    Word(word="young", translation="", part_of_speech=""),
    Word(word="while", translation="", part_of_speech=""),
    Word(word="mean", translation="", part_of_speech=""),
    Word(word="keep", translation="", part_of_speech=""),
    Word(word="let", translation="", part_of_speech=""),
    Word(word="great", translation="", part_of_speech=""),
    Word(word="seem", translation="", part_of_speech=""),
    Word(word="group", translation="", part_of_speech=""),
    Word(word="hand", translation="", part_of_speech=""),
    Word(word="talk", translation="", part_of_speech=""),
    Word(word="every", translation="", part_of_speech=""),
    Word(word="where", translation="", part_of_speech=""),
    Word(word="American", translation="", part_of_speech=""),
    Word(word="show", translation="", part_of_speech=""),
    Word(word="part", translation="", part_of_speech=""),
    Word(word="might", translation="", part_of_speech=""),
    Word(word="against", translation="", part_of_speech=""),
    Word(word="place", translation="", part_of_speech=""),
    Word(word="over", translation="", part_of_speech=""),
    Word(word="such", translation="", part_of_speech=""),
    Word(word="again", translation="", part_of_speech=""),
    Word(word="each", translation="", part_of_speech=""),
    Word(word="tight", translation="", part_of_speech=""),
    Word(word="program", translation="", part_of_speech=""),
    Word(word="doctor", translation="", part_of_speech=""),
    Word(word="color", translation="", part_of_speech=""),
    Word(word="case", translation="", part_of_speech=""),
    Word(word="maid", translation="", part_of_speech=""),
    Word(word="do", translation="", part_of_speech=""),
    Word(word="question", translation="", part_of_speech=""),
    Word(word="during", translation="", part_of_speech=""),
    Word(word="grocery", translation="", part_of_speech=""),
    Word(word="store", translation="", part_of_speech=""),
    Word(word="number", translation="", part_of_speech=""),
    Word(word="hospital", translation="", part_of_speech=""),
    Word(word="hurt", translation="", part_of_speech=""),
    Word(word="pain", translation="", part_of_speech=""),
    Word(word="bathroom", translation="", part_of_speech=""),
    Word(word="taxi", translation="", part_of_speech=""),
    Word(word="pharmacy", translation="", part_of_speech=""),
    Word(word="government", translation="", part_of_speech=""),
    Word(word="help", translation="", part_of_speech=""),
    Word(word="country", translation="", part_of_speech=""),
    Word(word="turn", translation="", part_of_speech=""),
    Word(word="problem", translation="", part_of_speech=""),
    Word(word="start", translation="", part_of_speech=""),
    Word(word="end", translation="", part_of_speech=""),
    Word(word="few", translation="", part_of_speech=""),
    Word(word="lucky", translation="", part_of_speech=""),
    Word(word="bird", translation="", part_of_speech=""),
    Word(word="mad", translation="", part_of_speech=""),
    Word(word="hat", translation="", part_of_speech=""),
    Word(word="off", translation="", part_of_speech=""),
    Word(word="always", translation="", part_of_speech=""),
    Word(word="move", translation="", part_of_speech=""),
    Word(word="stay", translation="", part_of_speech=""),
    Word(word="night", translation="", part_of_speech=""),
    Word(word="cool", translation="", part_of_speech=""),
    Word(word="Mr.", translation="", part_of_speech=""),
    Word(word="point", translation="", part_of_speech=""),
    Word(word="believe", translation="", part_of_speech=""),
    Word(word="hold", translation="", part_of_speech=""),
    Word(word="today", translation="", part_of_speech=""),
    Word(word="tomorrow", translation="", part_of_speech=""),
    Word(word="large", translation="", part_of_speech=""),
    Word(word="all", translation="", part_of_speech=""),
    Word(word="must", translation="", part_of_speech=""),
    Word(word="bring", translation="", part_of_speech=""),
    Word(word="happen", translation="", part_of_speech=""),
    Word(word="next", translation="", part_of_speech=""),
    Word(word="without", translation="", part_of_speech=""),
    Word(word="ice", translation="", part_of_speech=""),
    Word(word="under", translation="", part_of_speech=""),
    Word(word="water", translation="", part_of_speech=""),
    Word(word="room", translation="", part_of_speech=""),
    Word(word="write", translation="", part_of_speech=""),
    Word(word="mother", translation="", part_of_speech=""),
    Word(word="speak", translation="", part_of_speech=""),
    Word(word="area", translation="", part_of_speech=""),
    Word(word="father", translation="", part_of_speech=""),
    Word(word="national", translation="", part_of_speech=""),
    Word(word="money", translation="", part_of_speech=""),
    Word(word="story", translation="", part_of_speech=""),
    Word(word="fact", translation="", part_of_speech=""),
    Word(word="month", translation="", part_of_speech=""),
    Word(word="right", translation="", part_of_speech=""),
    Word(word="book", translation="", part_of_speech=""),
    Word(word="eye", translation="", part_of_speech=""),
    Word(word="job", translation="", part_of_speech=""),
    Word(word="word", translation="", part_of_speech=""),
    Word(word="though", translation="", part_of_speech=""),
    Word(word="business", translation="", part_of_speech=""),
    Word(word="issue", translation="", part_of_speech=""),
    Word(word="side", translation="", part_of_speech=""),
    Word(word="kind", translation="", part_of_speech=""),
    Word(word="long", translation="", part_of_speech=""),
    Word(word="short", translation="", part_of_speech=""),
    Word(word="both", translation="", part_of_speech=""),
    Word(word="won", translation="", part_of_speech=""),
    Word(word="little", translation="", part_of_speech=""),
    Word(word="house", translation="", part_of_speech=""),
    Word(word="home", translation="", part_of_speech=""),
    Word(word="yes", translation="", part_of_speech=""),
    Word(word="friend", translation="", part_of_speech=""),
    Word(word="Monday", translation="", part_of_speech=""),
    Word(word="Tuesday", translation="", part_of_speech=""),
    Word(word="Wednesday", translation="", part_of_speech=""),
    Word(word="Thursday", translation="", part_of_speech=""),
    Word(word="Friday", translation="", part_of_speech=""),
    Word(word="Saturday", translation="", part_of_speech=""),
    Word(word="Sunday", translation="", part_of_speech=""),
    Word(word="stand", translation="", part_of_speech=""),
    Word(word="sit", translation="", part_of_speech=""),
    Word(word="jump", translation="", part_of_speech=""),
    Word(word="crawl", translation="", part_of_speech=""),
    Word(word="please", translation="", part_of_speech=""),
    Word(word="thanks", translation="", part_of_speech=""),
    Word(word="smart", translation="", part_of_speech=""),
    Word(word="brush", translation="", part_of_speech=""),
    Word(word="self", translation="", part_of_speech=""),
    Word(word="important", translation="", part_of_speech=""),
    Word(word="line", translation="", part_of_speech=""),
    Word(word="snow", translation="", part_of_speech=""),
    Word(word="service", translation="", part_of_speech=""),
    Word(word="provide", translation="", part_of_speech=""),
    Word(word="law", translation="", part_of_speech=""),
    Word(word="city", translation="", part_of_speech=""),
    Word(word="car", translation="", part_of_speech=""),
    Word(word="truck", translation="", part_of_speech=""),
    Word(word="president", translation="", part_of_speech=""),
    Word(word="learn", translation="", part_of_speech=""),
    Word(word="drive", translation="", part_of_speech=""),
    Word(word="real", translation="", part_of_speech=""),
    Word(word="fake", translation="", part_of_speech=""),
    Word(word="news", translation="", part_of_speech=""),
    Word(word="change", translation="", part_of_speech=""),
    Word(word="include", translation="", part_of_speech=""),
    Word(word="name", translation="", part_of_speech=""),
    Word(word="beautiful", translation="", part_of_speech=""),
    Word(word="coffee", translation="", part_of_speech=""),
    Word(word="live", translation="", part_of_speech=""),
    Word(word="Excuse", translation="", part_of_speech=""),
    Word(word="understand", translation="", part_of_speech=""),
    Word(word="cat", translation="", part_of_speech=""),
    Word(word="am", translation="", part_of_speech=""),
    Word(word="dinner", translation="", part_of_speech=""),
    Word(word="buy", translation="", part_of_speech="")
    ]
    db.session.add_all(words)
    db.session.commit()

    phrases = [
    Phrase(phrase="I am happy.", translation=""),
    Phrase(phrase="You are tall.", translation=""),
    Phrase(phrase="He is a student.", translation=""),
    Phrase(phrase="She is beautiful.", translation=""),
    Phrase(phrase="It is a cat.", translation=""),
    Phrase(phrase="Where do you live?", translation=""),
    Phrase(phrase="What is your name?", translation=""),
    Phrase(phrase="How are you?", translation=""),
    Phrase(phrase="Do you like coffee?", translation=""),
    Phrase(phrase="Please and thank you.", translation=""),
    Phrase(phrase="Excuse me.", translation=""),
    Phrase(phrase="I don't understand.", translation=""),
    Phrase(phrase="Can you repeat that, please?", translation=""),
    # Add more common phrases and expressions here
    ]

    db.session.add_all(phrases)
    db.session.commit()

    lesson1 = Lesson(
        title = 'Pronouns',
        difficulty = 'Beginner',
        user_id = None,
        description = " This is learning the Basics - 1"
    )
    lesson1.words.extend(words[0:13])

    lesson2 =Lesson(
        title = 'Verbs',
        difficulty = 'Beginner',
        user_id = None,
        description = " This is learning the Basics - 2"
    )
    lesson2.words.extend(words[24:34])

    lesson3 = Lesson(
        title = 'Adjectives',
        difficulty = 'Beginner',
        user_id = None,
        description = " This is learning the Basics - 3"
    )
    lesson3.words.extend(words[14:23])

    lesson4 = Lesson(
        title = 'Etiquette',
        difficulty = 'Intermediate',
        user_id = None,
        description = " Learning to form Sentences - 1"  
    )
    lesson4.phrases.extend(phrases[9:])

    lesson5 = Lesson(
        title = 'Describe',
        difficulty = 'Intermediate',
        user_id = None,
        description = " Learning to form Sentences - 2" 
    )
    lesson5.phrases.extend(phrases[0:4])

    lesson6 = Lesson(
        title = 'Questions',
        difficulty = 'Intermediate',
        user_id = None,
        description = " Learning to form Sentences - 3" 
    )
    lesson6.phrases.extend(phrases[5:8])

    db.session.add(lesson1)
    db.session.add(lesson2)
    db.session.add(lesson3)
    db.session.add(lesson4)
    db.session.add(lesson5)
    db.session.add(lesson6)
    db.session.commit()

def undo_lessons():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.lessons RESTART IDENTITY CASCADE;")
        db.session.execute(f"TRUNCATE table {SCHEMA}.lessons_words RESTART IDENTITY CASCADE;")
        db.session.execute(f"TRUNCATE table {SCHEMA}.lessons_phrases RESTART IDENTITY CASCADE;")
        db.session.execute(f"TRUNCATE table {SCHEMA}.words RESTART IDENTITY CASCADE;")
        db.session.execute(f"TRUNCATE table {SCHEMA}.phrases RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM lessons"))
        db.session.execute(text("DELETE FROM lessons_words"))
        db.session.execute(text("DELETE FROM lessons_phrases"))
        db.session.execute(text("DELETE FROM words"))
        db.session.execute(text("DELETE FROM phrases"))
    
    db.session.commit()