"""empty message

Revision ID: 1003a55e912a
Revises: cffb8ee43437
Create Date: 2025-01-15 16:46:22.234895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1003a55e912a'
down_revision = 'cffb8ee43437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_of_speech', sa.String(length=25), nullable=True))
        batch_op.drop_column('part_of_speach')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_of_speach', sa.VARCHAR(length=25), nullable=True))
        batch_op.drop_column('part_of_speech')

    # ### end Alembic commands ###
