"""empty message

Revision ID: 87f6eacfd40f
Revises: 7850841bcc94
Create Date: 2025-03-04 16:07:01.861075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f6eacfd40f'
down_revision = '7850841bcc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=2048), nullable=True))
        batch_op.drop_column('audio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
