"""empty message

Revision ID: ed8f8498a00e
Revises: d2d46ab9bc62
Create Date: 2025-01-17 09:45:56.258892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8f8498a00e'
down_revision = 'd2d46ab9bc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.drop_column('learned')

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('learned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learned', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('phrases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learned', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
