"""Remove question/answer Columns and added the Question and Answer Model and association lesson_questions

Revision ID: 20ff36b6a54c
Revises: 9c6effbae37f
Create Date: 2025-04-07 15:57:05.306083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ff36b6a54c'
down_revision = '9c6effbae37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=25), nullable=False),
    sa.Column('audio_file', sa.String(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_question',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'question_id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('questions')
        batch_op.drop_column('answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('questions', sa.VARCHAR(), nullable=True))

    op.drop_table('lesson_question')
    op.drop_table('answers')
    op.drop_table('questions')
    # ### end Alembic commands ###
