"""empty message

Revision ID: 5f095570bbb8
Revises: a52ef0307a38
Create Date: 2025-02-25 14:28:33.525702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f095570bbb8'
down_revision = 'a52ef0307a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('audio')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=25), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('questions')

    # ### end Alembic commands ###
