"""empty message

Revision ID: 7850841bcc94
Revises: 5f095570bbb8
Create Date: 2025-02-26 17:29:37.597787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7850841bcc94'
down_revision = '5f095570bbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('score')
        batch_op.drop_column('level')

    # ### end Alembic commands ###
